#server
server:
  port: 10000

spring:
  datasource:
    hikari:
      #MyBatis
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: hr
      password: hr

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect # Oracle dialect for Hibernate
    hibernate:
      ddl-auto: update # Automatically create/update tables (use 'none' for production)
    properties:
      hibernate:
        use_sql_comments: true # Enable SQL comments in logs

  servlet:
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 40MB
